### ISSUE TITLE
Allow specifying MusicBrainz release for disc IDs that show up in more than one release

### ISSUE THREAD

**Issue by gnafuthegreat** [cyanreg/cyanrip#13]
I'd like the option to specify the MusicBrainz release ID for discs that are included in more than one release.  For example, this disc shows up in two releases:

https://musicbrainz.org/cdtoc/mHvDYAXODTuDWZ8prKQhmcg0vYg-

The release affects things like date and label information.  Perhaps something like:

`--release-id af59aeec-de29-4b15-b04d-89c1f0ed2599`

in cases where cyanrip defaults to the "wrong" release for the user's particular edition.

**Comment by cyanreg** [comment]
Fixed
