### ISSUE TITLE
[Feature Suggestion] Display disc ID when a rip "fails" due to multiple release IDs.

### ISSUE THREAD

**Issue by gnafuthegreat** [cyanreg/cyanrip#15]
When ripping a disc with multiple MusicBrainz release IDs and no release specified, the rip stops and cyanrip helpfully displays the available release IDs.  It would be nice if the disc ID was shown as well in the event a user feels none of the current releases match their disc and they want to add it to another release in MusicBrainz.

Currently, you'd need to specify one of the available release IDs to start a rip long enough to see the discid listed in the opening output.

**Comment by gnafuthegreat** [comment]
I'm now realizing their doesn't appear to be an easy way to add a disc ID to a release within MusicBrainz, so maybe this isn't useful.

**Comment by gnafuthegreat** [comment]
Looking at the way whipper does it, I guess you'd need to craft a URL like this:

https://musicbrainz.org/cdtoc/attach?1+13+335947+150+20804+44965+85812+102950+128267+154809+192231+219953+241721+267345+288328+307175

to be able to add the disc ID to a release.  I was able to use the above URL to start the process of adding the disc ID to the US release of the album.

**Comment by cyanreg** [comment]
One day I'll add a feature to add the info to musicbrainz.
