### ISSUE TITLE
[Feature Request] Utilize the Disambiguation information from MusicBrainz.

### ISSUE THREAD

**Issue by gnafuthegreat** [cyanreg/cyanrip#16]
Some releases on MusicBrainz include information in a Disambiguation field to denote things like special editions or anniversary re-releases.  It appears some rippers just include this information on the end of the album title.  Here are examples of some such releases:

[Weezer](https://musicbrainz.org/artist/6fe07aa5-fec0-4eca-a456-f29bff451b04) have released six self-titled albums to date.  To differentiate, the traditional addition to the album title has related to the album cover's color.  So we have "Weezer (Blue Album)", "Weezer (Green Album)", etc.  MusicBrainz stores those extra titles in the albums' respective Disambiguation fields and displays it on the release page in parentheses after the main title.  Another extended example of this within Weezer's catalog is something like [this](https://musicbrainz.org/release/c4510228-2383-47ff-8f7f-f0e593d273ef), which is the "Deluxe Edition" of the "Blue Album".

Another example would be the 25th anniversary releases of Paul Simon's Graceland, like [this](https://musicbrainz.org/release/edf34eb7-9da6-45da-acd1-9261e6ff3901).

I'm not sure of the best way to handle this information.  I personally don't mind including it in the album title, but that is perhaps less "correct".  The issue with not including it in the title is that you might have all of the albums titled "Weezer" listed under the same album in a music player.  Otherwise, perhaps just pulling in this information and including it in the metadata so it's there would be nice.

In the meantime, a user can simply override the album title and include this information however they see fit.  I just wanted to document this case.

**Comment by gnafuthegreat** [comment]
Another idea connected to this: if it isn't difficult to get the Disambiguation field from MusicBrainz, could it be displayed alongside release IDs for discs that have more than one release available?  That could help a user choose a release ID without having to look it up on the MusicBrainz website.

**Comment by cyanreg** [comment]
Test with the [disambiguation](https://github.com/cyanreg/cyanrip/tree/disambiguation) branch?

**Comment by gnafuthegreat** [comment]
That looks great!  The more I think about it, the more I think it's best not to include the disambiguation field in the album title by default (I will probably only be manually adding it to the aforementioned Weezer releases), but having it listed where you have it should help reduce trips to the MusicBrainz website :-).

Is there any kind of "standard" metadata field where this information could/should be stored?  It would be nice to have this info stored in the files, even if nothing uses it.

**Comment by cyanreg** [comment]
I've put it in `release` for now. I'm always setting it, hopefully MB doesn't contain junk in `disambiguation` for albums.
