### ISSUE TITLE
Some discs have more than one "good" result in AccurateRip database.

### ISSUE THREAD

**Issue by gnafuthegreat** [cyanreg/cyanrip#17]
It appears that some discs have more than one "good" result in the AccurateRip database.  These seem to be given a confidence rating based on how many people have submitted that particular set of checksums for that particular disc.  cyanrip appears to only compare against the result with the highest confidence, where whipper appears to be able to compare against lower confidence results when the highest confidence result doesn't match.  That may also be entirely the wrong way to describe what's going on, but it's how I've come to understand it.

Attached are a couple examples of logs from both cyanrip and whipper to show how they report a different confidence rating and how cyanrip reports "inaccurate" where whipper reports "accurate".  You can see the checksums match between the two programs, so they're definitely getting the same results from the disc.

I'm sure AccurateRip's database isn't the most accessible, so I don't know how complex a "fix" for this would be.  I just wanted to log it in the hope that the AccurateRip lookup can be improved in the future.  Please let me know if I can provide additional information about specific discs that present this behavior.

[gordon-cyanrip.log](https://github.com/cyanreg/cyanrip/files/5213312/gordon-cyanrip.log)
[gordon-whipper.log](https://github.com/cyanreg/cyanrip/files/5213313/gordon-whipper.log)

**Comment by gnafuthegreat** [comment]
Here is another example disc's logs:

[sound_of_silver-cyanrip.log](https://github.com/cyanreg/cyanrip/files/5213397/sound_of_silver-cyanrip.log)
[sound_of_silver-whipper.log](https://github.com/cyanreg/cyanrip/files/5213398/sound_of_silver-whipper.log)

It might also be worth mentioning that whipper reports confidence x out of y.  So for Gordon, it showed a confidence of 70-something out of 100-something (the numbers varied slightly, so it may have been 76/111, 75/112, etc.); and for Sound of Silver, it showed a confidence of 58-60/200.

**Comment by cyanreg** [comment]
I think I found the issue here when working on enhanced CD. It had records for both pregap-included and pregap-excluded, and I guess some discs only have a single version (in case of the above, pregap-included only).
