### ISSUE TITLE
Malformed disc ID and submission URL for PlayStation disc with audio tracks.

### ISSUE THREAD

**Issue by gnafuthegreat** [cyanreg/cyanrip#19]
I seem to get an invalid disc ID when I try to rip a PlayStation disc with audio tracks at the end.  For example, disc one of Lunar gives me this:

https://musicbrainz.org/cdtoc/attach?toc=1+3+261488+246922+258219&tracks=3&id=.A8KH4tSiiHfbJzXPyWJghuCyOY-

I also tried running cyanrip on a cdrdao rip of the same disc, and I got a different TOC and disc ID:

https://musicbrainz.org/cdtoc/attach?toc=1+3+261338+246772+258069&tracks=3&id=buK8JSCWgFudBEX4H6Ye4KxLQ3E-

Passing `-n` to get a quick rip going did rip and encode the audio tracks, and I'm attaching the log from that.

I would consider this very low priority--I'm certainly not planning on ripping the audio tracks from my PlayStation games anytime soon--but I thought it could potentially point to a more serious issue, so I wanted to log it.  Here are some pages with release information for this game:

https://musicbrainz.org/release/a1f8bb08-ec5c-4ae5-af4d-7576b8c4af90

http://redump.org/disc/2676/

[lunar-d1.log](https://github.com/cyanreg/cyanrip/files/5249967/lunar-d1.log)

**Comment by gnafuthegreat** [comment]
It looks like whipper generates a third, still-incorrect disc ID:

https://musicbrainz.org/cdtoc/attach?toc=1+2+261488+246922+258219&tracks=2&id=zmaUtjIze5V2sZccikjwbBTZTu4-

**Comment by cyanreg** [comment]
Fixed in 6d4e19bc7
