### ISSUE TITLE
Please Verify SPDX License Identifier

### ISSUE THREAD

**Issue by sodface** [cyanreg/cyanrip#27]
Hello, I am packaging cyanrip for Alpine Linux and they prefer that the license be from the [SPDX License List](https://spdx.org/licenses/preview/) when possible. Can you clarify which I should use:

LGPL-3.0-only
LGPL-3.0-or-later

I've read the license you link to and I believe "LGPL-3.0-only" is the correct choice but just wanted to make sure. Thanks.

**Comment by cyanreg** [comment]
Hi,
The project's license is LGPL v2.1 or later, as shown on each file's header. The file header's license is what has historically been more important than the LICENSE file, and I seem to have copied the wrong license (GNU seem to prefer to silently discourage use of old license versions).
In any case, I've updated the LICENSE file to the correct LGPL v2.1 or later, so the license you should use is [https://spdx.org/licenses/preview/LGPL-2.1-or-later.html](https://spdx.org/licenses/preview/LGPL-2.1-or-later.html).
It's the same license as FFmpeg, where some of the code originated.

By the way, once you've packaged it, could you send a patch to add to the installation instructions, or just ping me so I could add it? Thanks.
