### ISSUE TITLE
Compiling for aarch64 termux platform

### ISSUE THREAD

**Issue by tathastu871** [cyanreg/cyanrip#29]
Compiles and installed using:
meson build
ninja -C build
ninja -C build install
Installs without error.

Runtime error:

```
++ WARN: could not retrieve file info for `image.nrg': No such file or directory
++ WARN: can't open nrg image file image.nrg for reading
Unable to init cdio context
```

Help solving it is needed

**Comment by cyanreg** [comment]
cyanrip works fine on aarch64, I've made quite a lot of rips under it.
You mentioned Termux, I'm assuming you're using Android. libcdio does not support Android, and I'm not sure Android even supports CD drives.

**Comment by tathastu871** [comment]
> cyanrip works fine on aarch64, I've made quite a lot of rips under it. You mentioned Termux, I'm assuming you're using Android. libcdio does not support Android, and I'm not sure Android even supports CD drives.

Android does support cd drives through otg usb connection.
Usb cd/dvd players can be mounted and played via otg. Also there are cd ripping apps on playstore(used them succesfully) present that can rip cds via otg connected player.

Termux has api temux-usb to access usb otg devices.

**Comment by cyanreg** [comment]
Still, it's not really our problem, you should report this to libcdio instead, since we use that to interface with CD drives on all platforms.
