### ISSUE TITLE
cyanrip -h should explain better how to choose the encoding

### ISSUE THREAD

**Issue by kbt12243** [cyanreg/cyanrip#30]
Hello,
I don't understand nor see how I can choose the encoding (MP3, opus...) in the only help manual there is, aka "cyanrip -h"
Slight Request for enhancement then: dedicate a whole line to this in the help manual :)
Thank you

**Comment by wiiaboo** [comment]
```-o <string>           Comma separated list of outputs```

Although it's not very obvious, there is a line for it in `-h` already.
It's better explained on [readme.md - CLI](https://github.com/cyanreg/cyanrip/blob/master/README.md#cli):
```Comma separated list of output formats, "help" to list all, default is flac```

**Comment by cyanreg** [comment]
Done, I added an output section to the readme: https://github.com/cyanreg/cyanrip#output
If it's still not clear enough, just put the name of the format (first column) after the `-o` parameter.
