### ISSUE TITLE
"Unknown disc" is written in "Album" tag.

### ISSUE THREAD

**Issue by summer-alice** [cyanreg/cyanrip#33]
Hey, I mainly want to check this is the intended behaviour. When ripping some CDs using v0.8.0 their "Album" tags start with "Unknown disc" and the actual title appended on (e.g. `Album:          Unknown discいくつもの絵`). This wasn't the case with v0.7.0 (I've downgraded and confirmed). Commit db18b53de384c55a6253a8a3945926759cd9a1b3 seems to be where the change occurred.

If this is the intended behaviour, do you mind telling me where I can correct this in MusicBrainz?

Thank you.

**Comment by cyanreg** [comment]
I think I saw where the error is and fixed it in 43255197df4f5b340bc713c4d937782e16dbf5b8, could you give it a test?
If so, I may have to do a 0.8.1.

**Comment by summer-alice** [comment]
Yep that's fixed it. Thank you :smile:.
