### ISSUE TITLE
Disc unknown in MusicBrainz gets ripped as album_artist/album

### ISSUE THREAD

**Issue by meersjo** [cyanreg/cyanrip#34]
I noticed today that a disc was not recognized (did not show title, artist etc) but still ripped. When I went to inspect the log, I found that there were a lot more mp3 files than I had allowed it to rip, and they were older.

I identified them by sound and tried again with that disc, too - both are unknown in MB. When using Picard to start entering the data, however, I found for both discs that there did exist a stub.

My guess is that the MB API return for "does not exist but has a stub" is sufficiently similar that the CyanRIP code continues ripping with the default variable contents.

**Comment by cyanreg** [comment]
I'm not sure what you mean by more, older mp3 files. Did you rip the CD before?
We need a discid to be attached to a musicbrainz release in order to recognize discs. The program prints a link for you to do that. Even if the disc exists in musicbrainz, without it being tagged over there with a discid, we can't match it.

**Comment by meersjo** [comment]
No, I ripped a *different* disc before, which also has a stub but no actual release in MB.

I was able to identify the older rip by ear, then used Picard to create the actual entries for both (which is when MB told me they already had a stub, even though a manual search did not show anything), and afterwards Cyan picked it up correctly.

The problem is that for some reason Cyan did not find the disc in MB but still continued ripping with variables set to defaults - and the only thing I can see different from other discs without MB data I'm ripping is that these two had a stub.

Sent from Nine
________________________________

**Comment by cyanreg** [comment]
Ah, I see what you mean, can replicate. All of my collection either has a release or is missing, but I found a weird CD compilation that had a stub.
Thanks for reporting, fixed in 8bc0a56e82ac5f05ffd75ae3a09cd516a7df51fa
