### ISSUE TITLE
Add (lib)fdk-aac support?

### ISSUE THREAD

**Issue by diizzyy** [cyanreg/cyanrip#37]
Unless I'm reading the code incorrectly it doesn't seem to support this library at all via ffmpeg, as it is superior it would be nice if it would be an option and/or possible default one.

**Comment by wiiaboo** [comment]
If you disable the built-in aac encoder and only include fdk-aac when compiling ffmpeg, I think `-o aac` will use it, but not sure.

**Comment by diizzyy** [comment]
I guess that works but it's a bit inconvenient.

**Comment by cyanreg** [comment]
Closing this. I am rewriting ffmpeg's aac encoder anyway.
