### ISSUE TITLE
ReplayGain support

### ISSUE THREAD

**Issue by cyanreg** [cyanreg/cyanrip#39]
Adding this issue as a question for users:

Would you like to see ReplayGain metadata generation supported?

**Comment by diizzyy** [comment]
I think it makes more sense to rely on rsgain ( https://github.com/complexlogic/rsgain/ ) rather than trying to add more functionality in that area.

**Comment by cyanreg** [comment]
Fixed by 5285205fda8812a07d3f056a336517c094181e39
