### ISSUE TITLE
Created directory : lacking permissions ?

### ISSUE THREAD

**Issue by gneuvill** [cyanreg/cyanrip#40]
Hi,

The directory created by cyanrip during a ripping has permissions : `drwx------` .
Would it be possible to have it set those to `drwxr-xr-x` per default ?
(Not a big deal, just a matter of convenience but my NAS client don't detect new directories with the former set of permissions)

Thanks for the nice piece of software !

**Comment by cyanreg** [comment]
Couldn't you instead properly setup groups on your NAS?
On mine, my torrent client runs as a different user, with a group to which my user has full access to, so ownership is shared.
Hardcoding permissions isn't really appropriate.

**Comment by gneuvill** [comment]
Yep, sure, or script the call to cyanrip to do the job. As I said, this is not much of a problem, it just so happens that your program behaves differently than EAC on that matter. So I figured that if you were to crack a new release one of these days, changing the default set of permissions wouldn't be much of a drag.
But anyway, that won't prevent me from using cyanrip, so feel free to close the issue if you deem it appropriate.

Thanks !
