### ISSUE TITLE
MinGW, GCC: Multiple deprecation warnings and cyanrip_encode.c.obj fails

### ISSUE THREAD

**Issue by LigH-de** [cyanreg/cyanrip#41]
I tried to build cyanrip using the [media-autobuild suite](https://github.com/m-ab-s/media-autobuild_suite) which usually worked well but now fails; apparently cyanrip uses an ffmpeg API which is now deprecated.

The suite collected several [log files](https://github.com/m-ab-s/media-autobuild_suite/files/10700972/logs.zip) while building, this archive should contain all details you may need, hopefully.

It is a set of Windows batch and Unix shell scripts which automate building Windows targets of ffmpeg or similar software and embedded codec libraries, keeping itself up-to-date in an MSYS2/MinGW environment.

**Comment by cyanreg** [comment]
Thanks, fixed with 50828926f70445cb46996438f9aa44a839ed4b7f
