### ISSUE TITLE
Track Numbering for Mixed Mode CDs

### ISSUE THREAD

**Issue by sodface** [cyanreg/cyanrip#44]
One of the CDs used for testing [deemphasis support](https://github.com/cyanreg/cyanrip/issues/42) was the original 1996 Quake CD which is a mixed mode game disk with track 1 being data and the audio tracks starting with track 2, which cyanrip by default names accordingly, so the first ripped audio track gets the filename `02 - Quake Theme.flac`.

This is probably a bit of an edge case that could be fixed by using a custom file name scheme (haven't tried yet) but maybe it makes sense to default to only numbering audio tracks and ignore data tracks?

I'm not really sure this would even be the right thing to do. Depending on where you look, the Quake Theme is either track 1 or Track 2 in the listing:

https://www.discogs.com/release/9447246-Nine-Inch-Nails-Quake
https://www.nin.wiki/Quake_Soundtrack

It's disconcerting to be "missing" track 1 when browsing through your audio collection though, it just doesn't look right.

**Comment by cyanreg** [comment]
You can use `-t 2=track=1` to override the track numbers. Once for each track -_-
Everyone seems to agree on the numbering for mixed CDs skipping data tracks, so yeah, I don't think it's worth adding an option.
If it's disconcerting, try hacking your player to add a shortcut as track 1 which would play the game. Probably not fun if you're randomly playing songs, but hey, it's never not the time for a quick Quake map clear.
