### ISSUE TITLE
New preemphasis logging improperly logs deemphasis forced

### ISSUE THREAD

**Issue by cpforbes** [cyanreg/cyanrip#45]
The new preemphasis logs show deemphasis forced when it was not forced.

I think cyanrip_log.c:85 should check settings.force_deemphasis

https://github.com/cyanreg/cyanrip/blob/b1b5c97ad2a3cb8fbf954b0671f6012e563ae901/src/cyanrip_log.c#L85-L88

**Comment by cyanreg** [comment]
Fixed by ef653cfe7ece02331efd2d147ca93d36e33fc5fc, thanks
