### ISSUE TITLE
Update README for default offset

### ISSUE THREAD

**Issue by sodface** [cyanreg/cyanrip#47]
https://github.com/cyanreg/cyanrip/blob/6179ad39dfa476944fba05530ead2a2c5d8c673f/README.md?plain=1#L83

> By default cyanrip will rip all tracks from the default CD drive with an offset of 0

Should be deleted or reworded because of https://github.com/cyanreg/cyanrip/commit/04d84d3321e098f83cee6d13c1e36ffceead3a67 ?

**Comment by cyanreg** [comment]
Thanks, fixed
