### ISSUE TITLE
Way to specify disc format (CD/HDCD) in folder structure

### ISSUE THREAD

**Issue by ibelieveinwhatileaveinthewaybehind** [cyanreg/cyanrip#50]
I organize my library like: `[Year] Artist - Album [DiscFormat FLAC]`. Is there a way to name folders like this without manually specifying CDs and HDCDs? I've got the rest down (`[{year}] {album_artist} - {album} [CD FLAC]` if curious) but can't find an option to specify the disc format. I've tried `{format}` but that just shows `FLAC`.

**Comment by cyanreg** [comment]
Sure, added in c06f9eed059e9b631c9c0a308d102eaaa4a9cd14
Use {media_type}
"media_type" is a standard tag I must have missed.
Thanks.
