### ISSUE TITLE
Don't embed cover

### ISSUE THREAD

**Issue by Daniel6372** [cyanreg/cyanrip#52]
cyanrip by default both downloads the cover to the output directory and embeds it in every each flac file.
A lot of covers are upwards of several MB in size and this can result in a significant total size increase (e.g. 3 MB size cover for 15 tracks will result in 45 MB additional size, which could make up 10-15% of the total size).

There should probably be an option to select between embedding cover, only downloading to a file and not downloading cover at all.

**Comment by cyanreg** [comment]
I'm running out of command line switches, do you REALLY need to save a few megabytes on a rip hundreds of megabytes?

**Comment by Daniel6372** [comment]
Personally I'd edit the tags after ripping anyway, but it would be a better default not to embed. It's a total waste of space and covers can be embedded manually by those who wish to. This is why an option would be ideal.

**Comment by cyanreg** [comment]
I may add an option, but I'm not making it a default. The whole point is **not** to edit any tags at all after ripping.

**Comment by cyanreg** [comment]
@Daniel6372 Added `-G` in d457cd5ae181931e4c6b86979ae7a1ab174004ab

**Comment by Daniel6372** [comment]
Thank you for adding the option!
