### ISSUE TITLE
Consider using release assets

### ISSUE THREAD

**Issue by diizzyy** [cyanreg/cyanrip#57]
Earlier this year GitHub announced that generated source archives are only stable for a year, this will likely cause major issues for anyone trying to package Cyanrip longterm. Please consider uploading release source code archives.

Reference:
https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by cyanreg** [comment]
Could you just use git tags? They're safer than a third party's code, and they're signed.

**Comment by diizzyy** [comment]
If you're referring to the "source code" packages (https://github.com/cyanreg/cyanrip/archive/refs/tags/v0.9.2.tar.gz and zip) these aren't guaranteed to be stable (see like above) over time.

For clarification, 
Example: https://github.com/libsndfile/libsndfile/releases/tag/1.2.2

**Comment by cyanreg** [comment]
I think with the recent .xz issues and everyone switching to git tags instead, this doesn't need to be open anymore.

**Comment by diizzyy** [comment]
Not sure what repos you're looking at but that doesn't seem to be the case for the majority but oh well...

**Comment by cyanreg** [comment]
If by assets you mean manually creating signed archives and manually uploading them upon release, I can do that.

**Comment by diizzyy** [comment]
That would be great, thanks in advance! :-)
