### ISSUE TITLE
Cd's gets encoded to 24-bit

### ISSUE THREAD

**Issue by cleanyoursockets** [cyanreg/cyanrip#59]
Hello,

Ripped cd's to alac today, the output gets encoded in 24-bit if using the -o alac argument.
It works fine if using -o flac argument.
Rips get stuck after first track if using -o wavpack argument, the messege is flushing encoders.

**Comment by cyanreg** [comment]
Are you using HDCD decoding?

**Comment by cleanyoursockets** [comment]
I'm not using HDCD encoding and i have made sure that the cd's i have used is not HDCD cd's. I only get 24-bit output when using alac, not with flac using the same cd and the same arguments.

**Comment by cyanreg** [comment]
Fixed the alac issue with d6dbba0adaca29712a644f22778db4bcf95af621, thanks.
As for wavpack, ffmpeg's encoder is extremely slow at high compression levels (as in, it takes many hours to encode 3 minutes of audio). I've reduced the compression level to something more manageable with 3f0ab4320556672fd5454f815bb1ae0acc7e356d.

**Comment by cleanyoursockets** [comment]
Thank for fixing the issue, looking forward to ripping some cd's : )

------- Original Message -------
Den torsdag 7 september 2023 kl. 7:03 em, Lynne ***@***.***> skrev:

**Comment by cleanyoursockets** [comment]
Hello again,

Will there be a point release with the new changes or do i have to wait for the bigger 1.0 to use the program with Alac again?

Kind regards,

Jonas

------- Original Message -------
Den torsdag 7 september 2023 kl. 7:15 em, Jonas ***@***.***> skrev:

**Comment by cyanreg** [comment]
No, with 5285205fda8812a07d3f056a336517c094181e39 1.0 has all features it needs. Just needs to be tested before it's released.
