### ISSUE TITLE
aac gets encoded with 96000hz sampling rate

### ISSUE THREAD

**Issue by Tupsi** [cyanreg/cyanrip#6]
was wondering if this is the intended behaviour. I saw in the code, that you are looking what the specific codec can do and if its above 44.1 you use that maximum, otherwise fall back to 44.1. Now for an audio cd this seems like overkill. I know that for opus encodes everyone tells you to not mess with the 48, but with aac it seems that using 44.1 like you do with flac wouldnt hurt either. Just a suggestion.

**Comment by ghost** [comment]
The code picks the lowest sample rate higher or equal to 44100hz, not the highest one. So for all codecs that's 44100hz, except for opus when its 48000hz.

**Comment by ghost** [comment]
Ah, I see the issue - the sample rates are not sorted. I'll fix it.

**Comment by ghost** [comment]
Fixed by e81671d6966cb5, thanks for telling me
