### ISSUE TITLE
(Feature request) Metadata enhancement

### ISSUE THREAD

**Issue by cleanyoursockets** [cyanreg/cyanrip#62]
Thanks for enhancing the metadata into the logfile in the latest release! It would be great if also Catalog Number and Label was added, thank you.

**Comment by cyanreg** [comment]
They should already be added if present.
https://github.com/cyanreg/cyanrip/blob/master/src/musicbrainz.c#L334-L342

**Comment by cleanyoursockets** [comment]
Thanks for getting back to me. I got curious and ripped a cd with present label and catalog number info in Musicbrainz library, i made shure i got the right release, and checked the logfile, still no info in the metadata. I used the latest rc1.

------- Original Message -------
Den måndag 18 september 2023 kl. 3:06 em, Lynne ***@***.***> skrev:
