### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by jgreene5** [cyanreg/cyanrip#63]
I have a large ripping project upcoming and would love to use cyanrip; it covers all the bases while all the gui rippers only do so piecemeal.  But I'm having some issues with the Windows build.  It may be just me (I'm no expert with command line), but I can't get pregap detection to work.  Cyanrip accepts my command line string, so I don't think I'm entering it incorrectly, but gaps always return "none signalled".  I did double-check with EAC to verify that the CD was not gapless.  It looks like this option didn't become available until version 1.0 and the latest Windows build shows 0.9 in command prompt; does it lag behind the main release in this regard?  Of less concern, my drive is a Plextor PX-5224 that has overread capabilities for both lead-in and lead-out, but with the overread option enabled, my rips fail to complete at 99.99%.

**Comment by cyanreg** [comment]
Known issue that with some drivers, cdparanoia lacks support for gaps.
