### ISSUE TITLE
[Feature Request] Metadata tagging via CSV

### ISSUE THREAD

**Issue by kpcenti** [cyanreg/cyanrip#64]
Is it possible to request metadata tagging via CSV file or something similar? I'm still trying to figure out cyranrip so I apologize if I don't make sense.

You would feed it a .csv and the first row being what tags to fill out, then the next rows being the actual data. 

It would look something like this as an example 

```
TRACK,TITLE,ARTIST,ALBUM,YEAR,ALBUM ARTIST,ISRC
1,UNFORGIVEN (Japanese Version),LE SSERAFIM\\Ado\\NILE RODGERS,UNFORGIVEN,2023-08-23,LE SSERAFIM,JPPO02302501
2,ANTIFRAGILE (Japanese Version),LE SSERAFIM,UNFORGIVEN,2023-08-23,LE SSERAFIM,JPPO02302501

```
Take note of the first row being whatever tags the user wants.

Thanks

**Comment by cyanreg** [comment]
Dupliicate of https://github.com/cyanreg/cyanrip/issues/58
