### ISSUE TITLE
Question: Keywords for -D option

### ISSUE THREAD

**Issue by ASopH** [cyanreg/cyanrip#66]
Hi,
I love this prog :-), but I need some information about the  -D option

I want to rip to \album artist\(date) album\cd-number.track - title.extension.

1. how to I get <album artist> --> Is there a list of keywords tro use for?
2. how I get only year in date 2000 from 31-12-2000 or 2000-12-31

Thank you very much for your effort

**Comment by cyanreg** [comment]
"how to I get --> Is there a list of keywords tro use for?"
A what?

**Comment by ASopH** [comment]
Hi,
sorry, is not my home language  - I want to rip to \album artist\(date) album\cd+tracknumber. track - title.extension,
but, in example [album artist] ist not known -  [ALBUM ARTIST] or [CD-NUMBER] I meant as keywords for building the directory string.
With DATE, ALBUM and TITLE it works.
I hope, it is clearly know. 

nice work :-)
ASopH

**Comment by cyanreg** [comment]
Oh, can you try ``-D "{album_artist} ({year}) - {album}"``?
The filenames should be already correct.

**Comment by ASopH** [comment]
That's it - I've missed the underscore ^^ Thanks

**Comment by cyanreg** [comment]
Sure, no problem
