### ISSUE TITLE
mingw-w64 clang: cyanrip_main expected expression

### ISSUE THREAD

**Issue by 1480c1** [cyanreg/cyanrip#68]
```c
../src/cyanrip_main.c:557:5: error: expected expression
  557 |     const int frames_before_disc_start = t->frames_before_disc_start;
      |     ^
```
clang is complaining about the initialization after the label. A simple fix might be to just do `repeat_ripping:;` but I don't know if that's preferred as it looks a bit ugly.

**Comment by cyanreg** [comment]
Could you experiment with it to find something it's happy with?

**Comment by 1480c1** [comment]
Simply using `sed -i 's/repeat_ripping:/repeat_ripping:;/' src/cyanrip_main.c` has worked. <https://stackoverflow.com/questions/8384388/variable-declaration-after-goto-label#8384505> mentions the same

**Comment by cyanreg** [comment]
Thanks for reporting
Fixed
