### ISSUE TITLE
Publish Dockerfile

### ISSUE THREAD

**Issue by vinicentus** [cyanreg/cyanrip#71]
Hi!
First of all, amazing work with this project!

Would it be possible to publish the dockerfile in this repo? That would enable us to easily build the docker image ourselves.
The reasoning being that currently it's not very transparent what you download if you use the official image ep76/cyanrip.
This is what docker hub shows for IMAGE LAYERS:
```
1
COPY /lib /lib # buildkit
2.59 MB
2
COPY /usr /usr # buildkit
37.59 MB
3
LABEL maintainer=https://github.com/eq76/docker-cyanrip
0 B
4
ENTRYPOINT ["/usr/local/bin/cyanrip"]
0 B
5
CMD ["-h"]
```
How can I trust that this repo is the only thing included in the image?

Also, once the dockerfile is published, it would be easy to automatically build and release the docker image to docker hub, using github actions.

**Comment by meersjo** [comment]
Seconded. I'm getting the "Unrecognised track atrribute" errors despite being on the most recent docker image; I want to build my own to see if I can get rid of those with different base builds.

**Comment by vinicentus** [comment]
I realize now that the dockerfile is actually available here: https://github.com/ep76/docker-cyanrip
