### ISSUE TITLE
Why compute ReplayGain with -K?

### ISSUE THREAD

**Issue by q3cpma** [cyanreg/cyanrip#74]
Isn't it a waste to compute it anyway if it's only put in the log file?

**Comment by cyanreg** [comment]
The album-wide values at the end of the log are generated via a separate instance and do not require any caching of audio data, so we get them for "free" (the cost is negligible, considering CD drives are  much slower than doing some math on each frame).
The values are still useful to distinguish between pressings and mastering.

**Comment by q3cpma** [comment]
I see, thanks for the fast reply.
