### ISSUE TITLE
Error when detecting libavcodec

### ISSUE THREAD

**Issue by FumoVite** [cyanreg/cyanrip#75]
Hello,

i am trying to install cyanrip.
When running meson build i get the following error:
Dependency libavcodec found: NO found 58.134.100 but need: '>= 59.24.100'
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency libavcodec found: NO (tried cmake)

src/meson.build:20:0: ERROR: Invalid version of dependency, need 'libavcodec' ['>= 59.24.100'] found '58.134.100'.

However, i have version 60.31.102 installed.
What am i doing wrong?
[meson-log.txt](https://github.com/cyanreg/cyanrip/files/13851328/meson-log.txt)

Thanks

**Comment by cyanreg** [comment]
pkg-config is picking up the wrong version, the one installed on the system. Not our fault.
Make sure pkg-config is able to find the correct version. `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/` may help.
