### ISSUE TITLE
Windows 10 install fails

### ISSUE THREAD

**Issue by msroth** [cyanreg/cyanrip#76]
Windows install fails with the following error:
C:\>cyanrip-win64.exe
++ WARN: could not retrieve file info for `image.nrg': No such file or directory
++ WARN: can't open nrg image file image.nrg for reading
Unable to init cdio context
Not sure where to go from here, was hoping to use this on Windows.

**Comment by cyanreg** [comment]
Sounds like you're either lacking drivers or a CD drive altogether. Check under device manager?

**Comment by msroth** [comment]
Thanks.  I was expecting this EXE to install something not actually do the rip.  Plugged in DVD reader and it worked great.

**Comment by cyanreg** [comment]
Glad it worked, cheers.
