### ISSUE TITLE
Ubuntu install fails

### ISSUE THREAD

**Issue by debsidian** [cyanreg/cyanrip#77]
Using the instructions found on the [Readme.md, Debian and derivatives](https://github.com/cyanreg/cyanrip/blob/master/README.md#debian-and-derivatives) section. The install is not successful.

My system:
OS: Ubuntu 23.10 x86_64
Kernel: 6.5.0-14-generic
Shell: bash 5.2.15
CPU: 13th Gen Intel i7-13700KF
GPU: NVIDIA GeForce RTX 4070
Memory: 11947MiB / 31917MiB

Steps to reproduce:

1. Open terminal
2. At the command prompt, type: sudo apt install cyanrip
3. Type your password for sudo
4. View response: "E: Unable to locate package cyanrip"
5. Re-try without sudo, you get the same response.

![Screenshot from 2024-01-11 16-01-07-obfuscated](https://github.com/cyanreg/cyanrip/assets/7727156/b97edea2-8f73-4301-a559-fc6337e0673f)

**Comment by cyanreg** [comment]
It's currently only in Ubuntu Noble's repositories (the nightly version in development)
https://launchpad.net/ubuntu/+source/cyanrip
You have to either install it directly from launchpad, or add Noble repositories for apt, or manually compile and install, or download Debian's .deb and install it manually.
