### ISSUE TITLE
First track of specific album results in empty file when ReplayGain activated

### ISSUE THREAD

**Issue by jdorn-eu** [cyanreg/cyanrip#78]
I bought a new CD this week (linked below), it's a rather short album with 8 tracks, nothing special as far as I can see. When I create a rip just with `cyanrip -s 6` then for some reason, the first track file will be a completely empty file. However, when I make a rip with `cyanrip -s 6 -K` then there is no issue. I tried this multiple times, and it's 100% reproducible for me.

I'm not sure what is going on, the machine has 8GB of RAM and even when I rip albums that are far longer (this one is just about 33 minutes) this problem does not occur. For me so far it only happens with this specific album and only when ReplayGain tagging is activated.

Would be happy to investigate more on this if anybody has an idea what to do.

## CD details

[🔗 MusicBrainz](https://musicbrainz.org/cdtoc/7NY3aXR36YNlyiVRfZF7HPd1jo4-)  [🔗 Amazon](https://www.amazon.co.jp/再燃-魚高ミチル/dp/B0CN9JZRRB)

## System details

💿
```
cyanrip 0.9.2 (af45a74)
System device:  /dev/cdrom
Device model:   TSSTcorp BDDVDW SE-506CB  TS01 SCSI CD-ROM
Offset:         +6 samples
Overread:       +1 frame
Overread mode:  fill with silence in lead-in/lead-out
Speed:          default (unchangeable)
C2 errors:      supported by drive
Paranoia level: max
Frame retries:  10
HDCD decoding:  disabled
Album Art:      Front (From: Cover Art DB)
Outputs:        flac
Disc number:    1
Total discs:    1
Disc tracks:    8
Tracks to rip:  all
DiscID:         7NY3aXR36YNlyiVRfZF7HPd1jo4-
Release ID:     cd0a3a47-73e8-4f03-bec0-d96e84ac23bb
CDDB ID:        5A07DA08
Disc MCN:       0000000000000
Album:          再燃
Album artist:   魚高ミチル
AccurateRip:    not found
Total time:     00:33:30.198
```
💻
```
uname -a
Linux 6.6.3-413.asahi.fc39.aarch64+16k #1 SMP PREEMPT_DYNAMIC Sat Jan 27 17:19:54 UTC 2024 aarch64 GNU/Linux
```

**Comment by cyanreg** [comment]
Could you post the full logfile?

Also, does the issue happen with `-l 1` (which rips only the first track, and nothing else). Feel free to use `-P 0` to speed the rip up, should only take a minute or so.

**Comment by cyanreg** [comment]
Burned an exact copy of the same album to a CD, and tried ripping it. Couldn't replicate.
I'll add a burn prep mode to produce a single .cue+.wav which is directly burnable.

Cheers for sharing!
