### ISSUE TITLE
Lack of write permission not handled properly

### ISSUE THREAD

**Issue by isti115** [cyanreg/cyanrip#80]
I kept getting a "core dumped" error while trying to rip a CD, and after a bit of trial and error I figured out that it was caused by the fact that I was trying to output into a directory, on which my user didn't have write permission.

A check for this with a meaningful error message would be the best solution, but since I'm not that much into writing C, I thought that I'd at least leave an issue here, as future users who encounter the same problem might find this particular possible root cause quicker this way.

**Comment by cyanreg** [comment]
Fixed in eb219a4144f0284d7c4a2dc6c08cdfe40d388ce2
Thanks
