### ISSUE TITLE
Cue sheet file type

### ISSUE THREAD

**Issue by crazD802** [cyanreg/cyanrip#81]
My cue sheet says, "FILE "05 - Give Thanks and Praises.flac" WAVE" for example. Should that not be FLAC at the end?

**Comment by cyanreg** [comment]
The [unofficial CUE sheet spec](https://wiki.hydrogenaud.io/index.php?title=Cue_sheet#A_single-file_cue_sheet_with_a_TRACK_01_INDEX_00_hidden_track) says that:
> Also note that the file referenced is [FLAC](https://wiki.hydrogenaud.io/index.php?title=FLAC), but the [WAVE](https://wiki.hydrogenaud.io/index.php?title=WAV) files type is used. For [MP3](https://wiki.hydrogenaud.io/index.php?title=MP3) files the file type "[MP3](https://wiki.hydrogenaud.io/index.php?title=MP3)" should be used, for [AIFF](https://wiki.hydrogenaud.io/index.php?title=AIFF) you should use "[AIFF](https://wiki.hydrogenaud.io/index.php?title=AIFF)", but for all other types "[WAVE](https://wiki.hydrogenaud.io/index.php?title=WAV)" is used.'
