### ISSUE TITLE
Incorrect TOC for Nine Inch Nails Broken

### ISSUE THREAD

**Issue by Citrodata** [cyanreg/cyanrip#84]
The Returned Toc is 15906:34:30 for the Last Track instead of 5:07

Logoutput
`Checking /dev/cdrom for cdrom...
                CDROM sensed: PLEXTOR  DVDR   PX-716A   1.11 SCSI CD-ROM

Opening drive...
Unable to find release info for this CD, and metadata hasn't been manually added!
Please help improve the MusicBrainz DB by submitting the disc info via the following URL:
https://musicbrainz.org/cdtoc/attach?toc=1+99+4294922146+182+4862+21867+43210+51925+76015+94625+94927+95230+95532+95835+96137+96440+96742+97045+97347+97650+97952+98255+98557+98860+99162+99465+99767+100070+100372+100675+100977+101280+101582+101885+102187+102490+102792+103095+103397+103700+104002+104305+104607+104910+105212+105515+105817+106120+106422+106725+107027+107330+107632+107935+108237+108540+108842+109145+109447+109750+110052+110355+110657+110960+111262+111565+111867+112170+112472+112775+113077+113380+113682+113985+114287+114590+114892+115195+115497+115800+116102+116405+116707+117010+117312+117615+117917+118220+118522+118825+119127+119430+119732+120035+120337+120640+120942+121245+121547+121850+122152+146897&tracks=99&id=Zrc5EWRCa.PoBbwYmwmY52.nVEI-
To continue add metadata via -a or -t, or ignore via -N!`

**Comment by cyanreg** [comment]
Could you test with the latest commit I just pushed?

**Comment by Citrodata** [comment]
That is with the latest.

**Comment by cyanreg** [comment]
I meant the one I pushed 5 minutes ago, e792434be790c1d7ef3fa3d94396ec2c862b81ee

**Comment by Citrodata** [comment]
Still
Checking /dev/cdrom for cdrom...
                CDROM sensed: PLEXTOR  DVDR   PX-716A   1.11 SCSI CD-ROM


Opening drive...
Unable to find release info for this CD, and metadata hasn't been manually added!
Please help improve the MusicBrainz DB by submitting the disc info via the following URL:
https://musicbrainz.org/cdtoc/attach?toc=1+99+4294922146+182+4862+21867+43210+51925+76015+94625+94927+95230+95532+95835+96137+96440+96742+97045+97347+97650+97952+98255+98557+98860+99162+99465+99767+100070+100372+100675+100977+101280+101582+101885+102187+102490+102792+103095+103397+103700+104002+104305+104607+104910+105212+105515+105817+106120+106422+106725+107027+107330+107632+107935+108237+108540+108842+109145+109447+109750+110052+110355+110657+110960+111262+111565+111867+112170+112472+112775+113077+113380+113682+113985+114287+114590+114892+115195+115497+115800+116102+116405+116707+117010+117312+117615+117917+118220+118522+118825+119127+119430+119732+120035+120337+120640+120942+121245+121547+121850+122152+146897&tracks=99&id=Zrc5EWRCa.PoBbwYmwmY52.nVEI-
To continue add metadata via -a or -t, or ignore via -N!

**Comment by Citrodata** [comment]
I know a Marilyn Manson one with the Same joke TOC worked fine

**Comment by cyanreg** [comment]
Thanks. Is this the correct CD pressing?
https://musicbrainz.org/cdtoc/19fnQqgwiLc4fX5tAcRG4H3xhAo-

**Comment by Citrodata** [comment]
This Release: https://musicbrainz.org/release/09b037e9-e182-3a98-b729-abdfaa5a951c
This DISC Id: https://musicbrainz.org/cdtoc/np_JbCIjZS742YFKTZ4PKfwjLkE-

**Comment by Citrodata** [comment]
I can rip it with redumper and give you the log if you need.

**Comment by Citrodata** [comment]
setcd -i /dev/sr0
/dev/sr0:
  Disc found in drive: audio disc
    99 Tracks, 1--99
    Total playing time 37 minutes and 45 seconds

**Comment by cyanreg** [comment]
Was able to replicate with a close-enough copy of the album. Just pushed 67ad9705da84a1fc5837c92314a7f75239b05642 which should help.
Could you test again?

**Comment by Citrodata** [comment]
Checking /dev/cdrom for cdrom...
                CDROM sensed: PLEXTOR  DVDR   PX-716A   1.11 SCSI CD-ROM


Opening drive...
Multiple releases found in database for DiscID RQ9yuzEHF_fzexjCzj46KcdIaHA-:
    1 (ID: 8f014c6f-9f1c-3cab-ac03-12282456dfa1): Broken (JP) (1992-11-28)
    2 (ID: 09b037e9-e182-3a98-b729-abdfaa5a951c): Broken (GB) (1992-10-05)
    3 (ID: 249f22c9-e7d6-3ba8-a227-620f7f8fa9d3): Broken (JP) (1996-08-21)

Please specify which release to use by adding the -R argument with an index or ID.

Its Fixed yey

**Comment by cyanreg** [comment]
Thanks for testing
