### ISSUE TITLE
[Question] C2 error - drive

### ISSUE THREAD

**Issue by TJFOE** [cyanreg/cyanrip#88]
Hello,

I have 2 drives. One shows in *.log: C2 errors:      supported by drive

The other "unsupported by drive". How does cyanrip handle the one drive, which supports C2 errors? Or: How what can I do, that this drive-behaviour is ignored?

I am asking because I remember EAC that has the option to uncheck this behaviour.

Regards
Thomas

**Comment by cyanreg** [comment]
Handling is automatic. You don't have to do anything.
If you'd like to rely on the drive to do error correction, you can use `-P0`, but there's no reason to ever use it.
