### ISSUE TITLE
encoding failed

### ISSUE THREAD

**Issue by Tupsi** [cyanreg/cyanrip#9]
I am compiling cyanrip via the media-autobuild script on windows (so mingw). This worked in the past reasonably well, but now I got a suspiciously small file (only 6MB compared to the old one working with 47MB). Running it seems to work until the programm gets to the encoding part after ripping; here it always says "encoding failed" no matter what coder I try and I end up with a tiny file. Opening reveals that it only has some meta data in it, but nothing more.

I tried to compile it myself on the shell by going by your instructions, but ninja gives me this and I have no clue how to get rid of that double mentioning, so maybe you could give me a pointer?

`$ ninja -v -C build
ninja: Entering directory `build'
[1/4] gcc @src/25a6634@@cyanrip@exe/cyanrip_log.c.obj.rsp
[2/4] gcc @src/25a6634@@cyanrip@exe/cyanrip_encode.c.obj.rsp
[3/4] gcc @src/25a6634@@cyanrip@exe/cyanrip_main.c.obj.rsp
[4/4] gcc @src/cyanrip.exe.rsp
FAILED: src/cyanrip.exe
gcc @src/cyanrip.exe.rsp
C:/ffmpegbuild/local64/lib/libsrt.a(md5.cpp.o):md5.cpp:(.text+0x890): multiple definition of `md5_init'
C:/ffmpegbuild/msys64/mingw64/lib/libssh.a(libcrypto.c.obj):(.text+0xa30): first defined here
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
`
Although I am not even sure I should be able to compile that manually without other stuff going on in the main script, because if I remove the .exe the media-autobuild script created somehow, my manuell try does not give me the crippled version, so I was wondering if you rely on external programs now with 0.2.0 and ffmpeg and the mentioned libraries have to be present in the same directory or something like that for cyanrip to work properly?

For reference, the version I managed to build and which does encoding ist ce3cc0d523-git

**Comment by wiiaboo** [comment]
That doesn't have anything to do with cyanrip. All things that use that FFmpeg compilation will complain about that multiple definition error unless you stop including them (libssh and libsrt) or add `-Wl,--allow-multiple-definition` to LDFLAGS.
