### ISSUE TITLE
Error in MB-library

### ISSUE THREAD

**Issue by TJFOE** [cyanreg/cyanrip#91]
I wanted to rip a CD from 1995 - Ana Caram: Bossa Nova
https://musicbrainz.org/release/94b76471-d52e-490c-ba1f-e89549ec1f0b

Cyanrip doesn't recognize this CD. The same way as also MusicBrainz Picard doesn't do.
The MB-DiscID (identified by the attached cyanrip-logfile): zDuUyDx3QecX6VgQLa5RXn4cjGk-

The correct DiscID: vFtPy4Li.MsURsBUAbW1UJ.aI00-

The reason for this error is that there is a wrong return from the MB-library "discid_get_id". From here the wrong DiscID results.

Using "discid_get_webservice_url" you can see the correct DiscID (attached picture).

Do this:
https://musicbrainz.org/ws/2/discid/vFtPy4Li.MsURsBUAbW1UJ.aI00-
-> Here you get the ReleaseID:
<release id="94b76471-d52e-490c-ba1f-e89549ec1f0b">

http://musicbrainz.org/ws/2/release/[release ID]?inc=aliases+artist-credits+labels+discids+recordings
So you get the whole XML-file to
http://musicbrainz.org/ws/2/release/94b76471-d52e-490c-ba1f-e89549ec1f0b?inc=aliases+artist-credits+labels+discids+recordings

[Unknown disc (ZDUU)_cyanrip.log](https://github.com/user-attachments/files/15596108/Unknown.disc.ZDUU._cyanrip.log)
![discid_get_webservice_url__Ana_Caram_Bossa_Nova](https://github.com/cyanreg/cyanrip/assets/10260152/f1adbdad-92c7-4ead-bae3-51c25d3e6778)

**Comment by cyanreg** [comment]
Are you use you don't have a different pressing?

**Comment by TJFOE** [comment]
No I don't have a different pressing. There is only one from Chesky.

You can see on my link above that the CD in MB-Website has an other value than caynrip and musicbrainz picard give back (and do not find this CD.

Time ago I have coded a windows-program, which uses the last *.dll and there the correct DiscID is found. But only about the XML-file and "discid_get_webservice_url".

Calling "discid_get_id" via the '.dll gives the wrong DiscID which comes over from cyanrip.

**Comment by TJFOE** [comment]
I opened a ticket at MB "libdiscid".

**Comment by TJFOE** [comment]
Cyanrip:
https://musicbrainz.org/cdtoc/attach?toc=1+12+217800+150+17275+32650+47325+73252+92455+108094+131616+146891+164894+177421+196956&tracks=12&id=zDuUyDx3QecX6VgQLa5RXn4cjGk-

cdrecord dev=/dev/sr1 -toc
-> (Ana Caram, Bossa Nova):
track:   1 lba:             0 (            0) 00:02:00 adr: 1 control: 0 mode: -1
track:   2 lba:     17125 (    68500) 03:50:25 adr: 1 control: 2 mode: -1
track:   3 lba:     32500 (   130000) 07:15:25 adr: 1 control: 2 mode: -1
track:   4 lba:     47175 (   188700) 10:31:00 adr: 1 control: 2 mode: -1
track:   5 lba:     73102 (   292408) 16:16:52 adr: 1 control: 2 mode: -1
track:   6 lba:     92305 (   369220) 20:32:55 adr: 1 control: 2 mode: -1
track:   7 lba:    107944 (   431776) 24:01:19 adr: 1 control: 2 mode: -1
track:   8 lba:    131466 (   525864) 29:14:66 adr: 1 control: 2 mode: -1
track:   9 lba:    146741 (   586964) 32:38:41 adr: 1 control: 2 mode: -1
track:  10 lba:    164744 (   658976) 36:38:44 adr: 1 control: 2 mode: -1
track:  11 lba:    177271 (   709084) 39:25:46 adr: 1 control: 2 mode: -1
track:  12 lba:    196806 (   787224) 43:46:06 adr: 1 control: 2 mode: -1
track:lout lba:    217650 (   870600) 48:24:00 adr: 1 control: 2 mode: -1

**Comment by TJFOE** [comment]
Everything is correct here. May be it is too simple and someone has edited the wrong DiscID at MB...?

![calculated](https://github.com/cyanreg/cyanrip/assets/10260152/c70b213c-0333-465b-91bf-72a6a2bf2745)

**Comment by TJFOE** [comment]
No one has yet responded to my ticket on MusicBrainz. However, I am now certain that someone has submitted the existing CD there with the wrong DiscID. I have therefore created a second release at MB, which is now recognized by the MB-library “discid_get_id”.

**Comment by cyanreg** [comment]
It happens. There's nothing weird in the TOC to suggest that cyanrip generates an incorrect discid, so yeah, either its a different pressing, or a rerelease, or whatever.
