### ISSUE TITLE
Can't play files during rip (Close audio file handles early)

### ISSUE THREAD

**Issue by Firepal** [cyanreg/cyanrip#92]
When ripping [under Windows], all the files are empty until the full CD is ripped.
During a rip operation, I wanna be able to play tracks as soon as the encode, RG and other processing is done.

**Comment by cyanreg** [comment]
Disable replaygain via `-K`. Like its written in the readme. It's not possible to output anything until replaygain is complete, unless you disable it.

**Comment by Firepal** [comment]
Ah, thanks for the clarification. I don't use ReplayGain anyway so this is a fine compromise.

**Comment by Firepal** [comment]
`-K` flag does make cyanrip output to the file, thanks.
foobar2k complains "File is already in use" when I try to play just-ripped files, but MPC-HC plays them fine.
