### ISSUE TITLE
Save data, flush, or skip tracks (feature request)

### ISSUE THREAD

**Issue by daviside** [cyanreg/cyanrip#97]
I'm running Sway/foot shells under Arch with an Aur build (0.9.3.1 with a generic Panasonic drive). I've only ripped a dozen CDs thusfar, with mixed success.

There is a feature that is sorely needed IMHO: a way of aborting the rip without losing valid tracks already successfully ripped/encoded.

One CD had 20 tracks and began to fail on the 17th. Tracks 1 thru 16 were captured quickly (the technical term is 'lickity-split'), but track 17 took an hour without significant progress, so I did a Ctrl-C and cyanrip eventually returned to the prompt... but all the track files (FLAC,WAV,PCM) were **empty**.

When I encountered a similar pattern with another CD (track 12 of 12 'died' and would not advance beyond 93%), I used a kill *pid* from another shell window, and again cyanrip returned to the prompt, but also again, all the previous track's data was lost.

I presume (without reading the code yet) that writes are buffered (memory mapped?) and the data is lost because all those previos tracks are not flushed...?

I know it is possible to re-rip, avoiding/excluding the damaged area by process of elimination and experimentation, but
Is there any way to exit gracefully when an endless drive error loop seems to occur? Or, perhaps accept a user signal to skip a troublesome track when encountered?

**Comment by cyanreg** [comment]
You have to disable loudness normalization with the `-K` parameter to get tracks to be immediately written out.
Since its libcdio which freezes, because the drive/driver just doesn't surrender, we can't do anything but try to detect, which is difficult.
